### ISSUE TITLE
Refactor to use the submission wrapper module

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/or-review-processor#4]
refactor to utilize the [Submission Wrapper module](https://github.com/topcoder-platform/topcoder-submission-api-wrapper)

**Comment by callmekatootie** [comment]
@cwdcwd Do we have a challenge api wrapper and scorecard api wrapper too?

**Comment by callmekatootie** [comment]
Code has been updated to use submission api wrapper - code is in dev. Shortly moving to prod.
